### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by TildenWinston** [opencardev/openauto#16]
Are the updated build instructions? 

I am attempting to compile openauto but I am running into the following issue:

/home/tilden/Documents/opencardev-openauto/src/autoapp/Service/AndroidAutoEntityFactory.cpp:74:47:   required from here
/usr/include/c++/11/ext/new_allocator.h:162:11: error: invalid new-expression of abstract class type ‘f1x::openauto::autoapp::service::AndroidAutoEntity’
  162 |         { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I have managed to get all of the dependencies installed and I have succeeded in compiling AASDK, but I have not be able to get past this class error. Is there something else I am doing wrong?

My core goal is to get an Intel based machine to act as an android auto head-unit. Happy to try alternative suggestions if anyone has other ways to achieve this

**Comment by Charlyo** [comment]
I do have the same exact error.

**Comment by KiruyaMomochi** [comment]
Although it's late, but maybe you need to use `development` branch of aasdk.
https://github.com/opencardev/openauto/commit/d5e16bc4aac53fe9206dd6fde6a327222b375c14#r99795707

There are still lots of CMake issues, but somehow I have finally built it with Nix. However I can't get any output after Android Auto started on my phone.
If you would like to test my build you can use
```bash
nix build github:KiruyaMomochi/openauto
```

**Comment by dicetrash** [comment]
Couldn't use development branch of aasdk, that branch uses openssl 2.0 and the FIPS_mode_set methods instead of the new ssl 3.0 fips module, fixed in newdev and I do not wish to downgrade ssl for this.

**Comment by matt2005** [comment]
should be fixed once pr #18 is merged

**Comment by Jtradamus** [comment]
I still have the same issue 
`/usr/include/c++/12/bits/stl_construct.h:119:7: error: invalid new-expression of abstract class type ‘f1x::openauto::autoapp::service::AndroidAutoEntity’
  119 |       ::new((void*)__p) _Tp(std::forward<_Args>(__args)...);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

Is there Any update?

**Comment by matt2005** [comment]
should be fixed now
